# basic
title: CodeSharp
subtitle: Stronger Better Faster Sharper
# favicon: favicon.ico

avatar: images/avatar.png
banner_small: images/cover.png
banner_large: images/cover.png

# disqus
# disqus_shortname: codesharpco

# social
social:
  github: https://github.com/Code-Sharp
  twitter: https://twitter.com/codesharpco

# nav #
nav:
  home: .
  archive: archives
  # about: about
  rss: atom.xml

# heox-renderre-sass
#node_sass:
#  outputStyle: nested
#  precision: 5
#  sourceComments: false


google_analytics: UA-98663639-3
